language: cpp

os: linux

# Use the latest supported distro, Focal, released in April 2020…
dist: focal

git:
  depth: 1

compiler:
  - clang
  - gcc

env:
  matrix:
    - BUILD_TYPE="Release"
    - BUILD_TYPE="Debug"

before_install:
  - sudo apt-get install -y libassimp-dev
  - sudo apt-get install -y libglfw3-dev

script:
  - mkdir build || exit 1
  - pushd build && { cmake -DCMAKE_CXX_FLAGS="-Wall" \
                           -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
                           -G Ninja ..; popd; } || exit 1
  - cmake --build build || exit 1
